### ISSUE TITLE
GUI Bug (Management View)

### ISSUE THREAD

**Issue by rweisse** [hftlclub/ng-iltis#72] opened 2017-11-25 10:36 UTC
Steps to reproduce:
Click:
1. Verwaltung
2. Produkte
3. Verwaltung
4. Kategorien
5. ...

Everytime the new view is just added to the current one (it should be replaced): Scroll down to see what I mean.

**Comment by fmalcher** [comment] 2017-11-25 11:00
![bildschirmfoto 2017-11-25 um 12 00 19](https://user-images.githubusercontent.com/1683147/33229873-39ccfe30-d1d8-11e7-8630-3bd87b8b10b7.png)

**Comment by fmalcher** [comment] 2017-11-25 11:05
Interestingly, I cannot reproduce this with my local copy... seems to be a version issue

**Comment by fmalcher** [comment] 2017-11-25 11:15
Reopened unitl definitely fixed

**Comment by fmalcher** [comment] 2017-11-25 12:21
couldnt see the bug anymore now.
can you double check this please and close this issue, @rweisse ?

**Closed** 2017-11-25 13:27 UTC
Labels: bug
